num_training_steps: 100_000
replay_buffer_size: 100_000
batch_size: 1024
lr: 1.0e-3
weight_decay: 1.0e-5
grad_norm_clip: 1000.0
log_every: 300
eval_every: 2_000
use_scheduler: true

max_episode_steps: 500
num_eval_episodes: 10

store_model: true

